OBJECTS= ./build/compiler.o ./build/cprocess.o
INCLUDE= -I./

all: ${OBJECTS}
	gcc main.c $(INCLUDES) $(OBJECTS) -g -o ./main

./build/compiler.o: ./compiler.c
	gcc ./compiler.c $(INCLUDE) -o ./build/compiler.o -g -c

./build/cprocess.o: ./cprocess.c
	gcc ./cprocess.c $(INCLUDE) -o ./build/cprocess.o -g -c

clean:
	rm ./main
	rm -rf $(OBJECTS)