OBJECTS=
INCLUDE= -I./

all: ${OBJECTS}
	gcc main.c $(INCLUDES) $(OBJECTS) -g -o ./main

./build/compiler.o: ./compiler.c
	gcc compiler.c -o ./build/compiler.o -g -c

clean:
	rm ./main
	rm -rf $(OBJECTS)